apiVersion: v1
kind: Service
metadata:
  name: Service 
  labels:
    app: Service

spec: 
  replicas: 3
  selector:
    app: Service
  template:
    metadata:
      labels:
        app: Service
    spec:
      containers:
      - name: Service 
        image: x
        ports:
        - name: http
          containerPort: 80