apiVersion: apps/v1
kind: Deployment
metadata:
  name: playdep 

spec:
  replicas: 1
  
  selector:
    matchLabels:
      app: playdep
  
  template:
    
    metadata:
      labels:
        app: playdep
    
    spec:
      containers:
      - name: playdep
        image: crnneo.azurecr.io/neo
        ports:
        - containerPort: 5000
          protocol: TCP
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
      imagePullSecrets:
       - name: regcred
