apiVersion: networking.k8s.io/v1
kind: Ingress 
metadata:
  name: playingress 
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: playservice
                port:
                  number: 5000
            path: /
            pathType: Prefix