apiVersion: v1
kind: Service 
metadata:
  name: playservice 

spec: # clusterIP, loadBalancer ( CLOUD LOADBALANCER ), nodePort
  selector:
    app: playdep  
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
