name:  CI

on:
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions@checkoutv3
    - name: build image
      run: |
        docker build -t $GITHUB_REPOSITORY:$GITHUB_SHA .
#"""
#jobs:
 # imagerepo:
    #runs_on: ubuntu-latest
    #steps:
    #- uses: actions@checkoutv3
    #- name: push_image
   #   working_directory: ./
 #     run: |
#        docker push #GITHUB_REPOSITORY:$GITHUB_SHA  """
