name: push_image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  push_image:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
    - uses: actions/checkout@v2
    - name: get tag
      id: tag
      uses: dawidd6/action-get-tag@v1

    - name: login
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.ACR_ENDPOINT }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: push
      uses: docker/build-push-action@v1
      with:
        push: true
        build-args: |
          version=latest
        tags: ${{ secrets.ACR_ENDPOINT }}
    
    - name: scan
      run: |
        wget https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb 
        sudo dpkg -i trivy_0.18.3_Linux-64bit.deb
        trivy 

